changelog:
  exclude:
    labels:
      - skip-changelog

  categories:
    - title: CI & Automation
      labels:
        - ci
        - build
        - dependencies
        - github_actions

    - title: Documentation
      labels:
        - docs

    - title: Features
      labels:
        - feat
        - feature
        - enhancement

    - title: Fixes
      labels:
        - fix
        - bug
        - bugfix

    - title: Other Changes
      labels:
        - improve
        - chore
        - refactor
        - style
        - test